# Generated by Django 6.0.3 on 2026-03-14 20:56

import simple_history.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalProducto',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('codigo', models.CharField(db_index=True, help_text='Código único interno del producto', max_length=50)),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('categoria', models.CharField(choices=[('MP', 'Materia Prima'), ('PI', 'Producto Importado'), ('PT', 'Producto Terminado'), ('SU', 'Sutura')], max_length=2)),
                ('unidad_medida', models.CharField(choices=[('UN', 'Unidad'), ('KG', 'Kilogramo'), ('MT', 'Metro'), ('LT', 'Litro'), ('CJ', 'Caja'), ('BR', 'Barra'), ('BL', 'Bloque')], default='UN', max_length=2)),
                ('requiere_anmat', models.BooleanField(default=False, help_text='Indica si el producto requiere habilitación ANMAT por importación')),
                ('numero_registro_anmat', models.CharField(blank=True, help_text='Número de registro ANMAT (si aplica)', max_length=100)),
                ('vencimiento_habilitacion_anmat', models.DateField(blank=True, help_text='Fecha de vencimiento de la habilitación ANMAT', null=True)),
                ('stock_minimo_seguridad', models.DecimalField(decimal_places=2, default=0, help_text='Stock mínimo de seguridad (colchón ante imprevistos)', max_digits=10)),
                ('tiempo_transito_dias', models.PositiveIntegerField(default=0, help_text='Días estimados desde orden hasta llegada al depósito')),
                ('tiempo_tramite_anmat_dias', models.PositiveIntegerField(default=0, help_text='Días estimados del trámite ANMAT (si aplica)')),
                ('consumo_promedio_mensual', models.DecimalField(blank=True, decimal_places=2, help_text='Calculado automáticamente o definido manualmente al inicio', max_digits=10, null=True)),
                ('consumo_manual', models.BooleanField(default=True, help_text='True = ingresado manualmente. False = calculado por el sistema')),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(blank=True, editable=False)),
                ('actualizado_en', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical Producto',
                'verbose_name_plural': 'historical Productos',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(help_text='Código único interno del producto', max_length=50, unique=True)),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('categoria', models.CharField(choices=[('MP', 'Materia Prima'), ('PI', 'Producto Importado'), ('PT', 'Producto Terminado'), ('SU', 'Sutura')], max_length=2)),
                ('unidad_medida', models.CharField(choices=[('UN', 'Unidad'), ('KG', 'Kilogramo'), ('MT', 'Metro'), ('LT', 'Litro'), ('CJ', 'Caja'), ('BR', 'Barra'), ('BL', 'Bloque')], default='UN', max_length=2)),
                ('requiere_anmat', models.BooleanField(default=False, help_text='Indica si el producto requiere habilitación ANMAT por importación')),
                ('numero_registro_anmat', models.CharField(blank=True, help_text='Número de registro ANMAT (si aplica)', max_length=100)),
                ('vencimiento_habilitacion_anmat', models.DateField(blank=True, help_text='Fecha de vencimiento de la habilitación ANMAT', null=True)),
                ('stock_minimo_seguridad', models.DecimalField(decimal_places=2, default=0, help_text='Stock mínimo de seguridad (colchón ante imprevistos)', max_digits=10)),
                ('tiempo_transito_dias', models.PositiveIntegerField(default=0, help_text='Días estimados desde orden hasta llegada al depósito')),
                ('tiempo_tramite_anmat_dias', models.PositiveIntegerField(default=0, help_text='Días estimados del trámite ANMAT (si aplica)')),
                ('consumo_promedio_mensual', models.DecimalField(blank=True, decimal_places=2, help_text='Calculado automáticamente o definido manualmente al inicio', max_digits=10, null=True)),
                ('consumo_manual', models.BooleanField(default=True, help_text='True = ingresado manualmente. False = calculado por el sistema')),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('pais_origen', models.CharField(max_length=100)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
                'ordering': ['nombre'],
            },
        ),
    ]
