# Generated by Django 6.0.3 on 2026-03-16 23:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Sector',
                'verbose_name_plural': 'Sectores',
                'ordering': ['nombre'],
            },
        ),
        migrations.AlterField(
            model_name='historicalproducto',
            name='codigo',
            field=models.CharField(db_index=True, help_text='Codigo unico interno del producto', max_length=50),
        ),
        migrations.AlterField(
            model_name='historicalproducto',
            name='consumo_promedio_mensual',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Calculado automaticamente o definido manualmente al inicio', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='historicalproducto',
            name='numero_registro_anmat',
            field=models.CharField(blank=True, help_text='Numero de registro ANMAT (si aplica)', max_length=100),
        ),
        migrations.AlterField(
            model_name='historicalproducto',
            name='requiere_anmat',
            field=models.BooleanField(default=False, help_text='Indica si el producto requiere habilitacion ANMAT por importacion'),
        ),
        migrations.AlterField(
            model_name='historicalproducto',
            name='stock_minimo_seguridad',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Stock minimo de seguridad', max_digits=10),
        ),
        migrations.AlterField(
            model_name='historicalproducto',
            name='tiempo_tramite_anmat_dias',
            field=models.PositiveIntegerField(default=0, help_text='Dias estimados del tramite ANMAT (si aplica)'),
        ),
        migrations.AlterField(
            model_name='historicalproducto',
            name='tiempo_transito_dias',
            field=models.PositiveIntegerField(default=0, help_text='Dias estimados desde orden hasta llegada al deposito'),
        ),
        migrations.AlterField(
            model_name='historicalproducto',
            name='vencimiento_habilitacion_anmat',
            field=models.DateField(blank=True, help_text='Fecha de vencimiento de la habilitacion ANMAT', null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='codigo',
            field=models.CharField(help_text='Codigo unico interno del producto', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='consumo_promedio_mensual',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Calculado automaticamente o definido manualmente al inicio', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='numero_registro_anmat',
            field=models.CharField(blank=True, help_text='Numero de registro ANMAT (si aplica)', max_length=100),
        ),
        migrations.AlterField(
            model_name='producto',
            name='requiere_anmat',
            field=models.BooleanField(default=False, help_text='Indica si el producto requiere habilitacion ANMAT por importacion'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='stock_minimo_seguridad',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Stock minimo de seguridad', max_digits=10),
        ),
        migrations.AlterField(
            model_name='producto',
            name='tiempo_tramite_anmat_dias',
            field=models.PositiveIntegerField(default=0, help_text='Dias estimados del tramite ANMAT (si aplica)'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='tiempo_transito_dias',
            field=models.PositiveIntegerField(default=0, help_text='Dias estimados desde orden hasta llegada al deposito'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='vencimiento_habilitacion_anmat',
            field=models.DateField(blank=True, help_text='Fecha de vencimiento de la habilitacion ANMAT', null=True),
        ),
        migrations.CreateModel(
            name='RequisitoCalidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('FOTO', 'Foto del producto'), ('PLANO', 'Plano tecnico'), ('CERT_MP', 'Certificado de materia prima'), ('CLV', 'CLV'), ('CARTA', 'Carta compromiso'), ('OTRO', 'Otro')], help_text='Tipo de documento de calidad', max_length=20)),
                ('descripcion', models.CharField(blank=True, help_text='Descripcion adicional del documento', max_length=200)),
                ('archivo', models.FileField(help_text='Archivo del documento (PDF, imagen, etc.)', upload_to='productos/calidad/')),
                ('fecha_carga', models.DateTimeField(auto_now_add=True)),
                ('vigente', models.BooleanField(default=True, help_text='Desmarcar si el documento fue reemplazado por una version mas nueva')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requisitos_calidad', to='productos.producto')),
            ],
            options={
                'verbose_name': 'Requisito de Calidad',
                'verbose_name_plural': 'Requisitos de Calidad',
                'ordering': ['tipo', '-fecha_carga'],
            },
        ),
        migrations.AddField(
            model_name='producto',
            name='sectores',
            field=models.ManyToManyField(blank=True, help_text='Sectores de la fabrica a los que se destina este producto', related_name='productos', to='productos.sector'),
        ),
    ]
