# Generated by Django 6.0.3 on 2026-03-17 00:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0003_sector_alter_historicalproducto_codigo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='sectores',
        ),
    ]
