# Generated by Django 6.0.3 on 2026-03-14 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProyeccionAgotamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dias_restantes', models.IntegerField(blank=True, help_text='Días hasta agotamiento estimado con consumo promedio actual', null=True)),
                ('fecha_agotamiento_estimada', models.DateField(blank=True, null=True)),
                ('fecha_calculo', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Proyección de Agotamiento',
                'verbose_name_plural': 'Proyecciones de Agotamiento',
            },
        ),
    ]
