# Generated by Django 6.0.3 on 2026-03-14 20:56

import simple_history.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalLote',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('numero_lote', models.CharField(max_length=100)),
                ('cantidad_inicial', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cantidad_actual', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estado', models.CharField(choices=[('BLOQUEADO', 'Bloqueado - pendiente ANMAT'), ('LIBERADO', 'Liberado - disponible'), ('AGOTADO', 'Agotado')], default='LIBERADO', max_length=20)),
                ('fecha_ingreso', models.DateField()),
                ('fecha_vencimiento', models.DateField(blank=True, help_text='Fecha de vencimiento o esterilización del lote', null=True)),
                ('certificado_calidad', models.TextField(blank=True, max_length=100, null=True)),
                ('observaciones', models.TextField(blank=True)),
                ('creado_en', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical Lote',
                'verbose_name_plural': 'historical Lotes',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalMovimientoStock',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ENTRADA', 'Entrada al depósito'), ('SALIDA', 'Salida / Consumo'), ('AJUSTE_POS', 'Ajuste positivo'), ('AJUSTE_NEG', 'Ajuste negativo'), ('BAJA_VEN', 'Baja por vencimiento'), ('BAJA_DAN', 'Baja por daño')], max_length=15)),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10)),
                ('motivo', models.CharField(blank=True, choices=[('VENTA', 'Venta / Entrega'), ('PRODUCCION', 'Consumo en producción'), ('DEVOLUCION', 'Devolución a proveedor'), ('BAJA', 'Baja (vencimiento / daño)'), ('OTRO', 'Otro')], max_length=20)),
                ('notas', models.TextField(blank=True)),
                ('fecha_hora', models.DateTimeField(blank=True, editable=False)),
                ('registrado_via_qr', models.BooleanField(default=False, help_text='True si fue registrado escaneando código QR desde celular')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical Movimiento de Stock',
                'verbose_name_plural': 'historical Movimientos de Stock',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Lote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_lote', models.CharField(max_length=100)),
                ('cantidad_inicial', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cantidad_actual', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estado', models.CharField(choices=[('BLOQUEADO', 'Bloqueado - pendiente ANMAT'), ('LIBERADO', 'Liberado - disponible'), ('AGOTADO', 'Agotado')], default='LIBERADO', max_length=20)),
                ('fecha_ingreso', models.DateField()),
                ('fecha_vencimiento', models.DateField(blank=True, help_text='Fecha de vencimiento o esterilización del lote', null=True)),
                ('certificado_calidad', models.FileField(blank=True, null=True, upload_to='certificados/')),
                ('observaciones', models.TextField(blank=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Lote',
                'verbose_name_plural': 'Lotes',
                'ordering': ['-fecha_ingreso'],
            },
        ),
        migrations.CreateModel(
            name='MovimientoStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ENTRADA', 'Entrada al depósito'), ('SALIDA', 'Salida / Consumo'), ('AJUSTE_POS', 'Ajuste positivo'), ('AJUSTE_NEG', 'Ajuste negativo'), ('BAJA_VEN', 'Baja por vencimiento'), ('BAJA_DAN', 'Baja por daño')], max_length=15)),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10)),
                ('motivo', models.CharField(blank=True, choices=[('VENTA', 'Venta / Entrega'), ('PRODUCCION', 'Consumo en producción'), ('DEVOLUCION', 'Devolución a proveedor'), ('BAJA', 'Baja (vencimiento / daño)'), ('OTRO', 'Otro')], max_length=20)),
                ('notas', models.TextField(blank=True)),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('registrado_via_qr', models.BooleanField(default=False, help_text='True si fue registrado escaneando código QR desde celular')),
            ],
            options={
                'verbose_name': 'Movimiento de Stock',
                'verbose_name_plural': 'Movimientos de Stock',
                'ordering': ['-fecha_hora'],
            },
        ),
        migrations.CreateModel(
            name='StockConsolidado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_disponible', models.DecimalField(decimal_places=2, default=0, help_text='Stock liberado y disponible para uso/venta', max_digits=10)),
                ('stock_bloqueado', models.DecimalField(decimal_places=2, default=0, help_text='Stock pendiente de aprobación ANMAT', max_digits=10)),
                ('stock_total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Stock Consolidado',
                'verbose_name_plural': 'Stocks Consolidados',
            },
        ),
    ]
