# Generated by Django 6.0.3 on 2026-03-15 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicallote',
            name='categoria',
            field=models.CharField(choices=[('MP', 'Materia Prima'), ('SE', 'Semielaborado'), ('IN', 'Insumos'), ('MA', 'Maquinaria')], default='IN', help_text='Categoría del lote ingresado', max_length=2),
        ),
        migrations.AddField(
            model_name='lote',
            name='categoria',
            field=models.CharField(choices=[('MP', 'Materia Prima'), ('SE', 'Semielaborado'), ('IN', 'Insumos'), ('MA', 'Maquinaria')], default='IN', help_text='Categoría del lote ingresado', max_length=2),
        ),
    ]
