# Generated by Django 6.0.3 on 2026-03-14 21:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('importaciones', '0002_initial'),
        ('productos', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertaProveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_evento', models.CharField(choices=[('DEMORA_EMB', 'Demora en embarque'), ('DEMORA_ADU', 'Demora en aduana'), ('DEMORA_ANM', 'Demora en tramite ANMAT'), ('CALIDAD', 'Problema de calidad en el lote'), ('ENT_INCOMP', 'Entrega incompleta'), ('CANCELACION', 'Cancelacion de orden'), ('PAGO', 'Problemas en pago'), ('OTRO', 'Otro')], max_length=20)),
                ('cantidad_eventos', models.PositiveIntegerField()),
                ('mensaje', models.TextField()),
                ('resuelta', models.BooleanField(default=False, help_text='Marcar como resuelta cuando se ajusten los parametros')),
                ('notas_resolucion', models.TextField(blank=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('resuelta_en', models.DateTimeField(blank=True, null=True)),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertas', to='productos.proveedor')),
                ('resuelta_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alertas_resueltas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Alerta de Proveedor',
                'verbose_name_plural': 'Alertas de Proveedores',
                'ordering': ['-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='EventoExtraordinario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('DEMORA_EMB', 'Demora en embarque'), ('DEMORA_ADU', 'Demora en aduana'), ('DEMORA_ANM', 'Demora en tramite ANMAT'), ('CALIDAD', 'Problema de calidad en el lote'), ('ENT_INCOMP', 'Entrega incompleta'), ('CANCELACION', 'Cancelacion de orden'), ('PAGO', 'Problemas en pago'), ('OTRO', 'Otro')], max_length=20)),
                ('fecha_evento', models.DateField()),
                ('descripcion', models.TextField(help_text='Descripcion detallada del evento ocurrido')),
                ('impacto_dias', models.PositiveIntegerField(blank=True, help_text='Dias de retraso o impacto estimado (si aplica)', null=True)),
                ('alerta_patron_generada', models.BooleanField(default=False, help_text='True si este evento disparo una alerta de patron con el proveedor')),
                ('parametro_ajustado', models.BooleanField(default=False, help_text='True si se ajustaron los tiempos de reposicion del proveedor')),
                ('notas_ajuste', models.TextField(blank=True, help_text='Descripcion del ajuste realizado en los parametros del proveedor')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('importacion', models.ForeignKey(help_text='Numero de orden de importacion afectada', on_delete=django.db.models.deletion.PROTECT, related_name='eventos', to='importaciones.importacion')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos_registrados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Evento Extraordinario',
                'verbose_name_plural': 'Eventos Extraordinarios',
                'ordering': ['-fecha_evento'],
            },
        ),
    ]
