# Generated by Django 6.0.3 on 2026-03-16 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alertaproveedor',
            name='dias_adicionales_recomendados',
            field=models.PositiveIntegerField(default=0, help_text='Dias adicionales recomendados para anticipar la proxima orden'),
        ),
        migrations.AlterField(
            model_name='alertaproveedor',
            name='cantidad_eventos',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
