# Generated by Django 6.0.3 on 2026-03-14 20:56

import simple_history.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConsumoMateriaPrima',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden_produccion', models.CharField(help_text='Número de orden de producción interna', max_length=100)),
                ('cantidad_consumida', models.DecimalField(decimal_places=3, max_digits=10)),
                ('fecha_consumo', models.DateField()),
                ('notas', models.TextField(blank=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Consumo de Materia Prima',
                'verbose_name_plural': 'Consumos de Materia Prima',
                'ordering': ['-fecha_consumo'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalLoteMateriaPrima',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('numero_lote', models.CharField(max_length=100)),
                ('proveedor_lote', models.CharField(blank=True, help_text='Nombre del proveedor según el certificado del lote', max_length=200)),
                ('cantidad_inicial', models.DecimalField(decimal_places=3, max_digits=10)),
                ('cantidad_actual', models.DecimalField(decimal_places=3, max_digits=10)),
                ('fecha_ingreso', models.DateField()),
                ('certificado_calidad', models.TextField(blank=True, max_length=100, null=True)),
                ('numero_certificado', models.CharField(blank=True, max_length=100)),
                ('activo', models.BooleanField(default=True)),
                ('observaciones', models.TextField(blank=True)),
                ('creado_en', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical Lote de Materia Prima',
                'verbose_name_plural': 'historical Lotes de Materia Prima',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='LoteMateriaPrima',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_lote', models.CharField(max_length=100)),
                ('proveedor_lote', models.CharField(blank=True, help_text='Nombre del proveedor según el certificado del lote', max_length=200)),
                ('cantidad_inicial', models.DecimalField(decimal_places=3, max_digits=10)),
                ('cantidad_actual', models.DecimalField(decimal_places=3, max_digits=10)),
                ('fecha_ingreso', models.DateField()),
                ('certificado_calidad', models.FileField(blank=True, null=True, upload_to='mp/certificados/')),
                ('numero_certificado', models.CharField(blank=True, max_length=100)),
                ('activo', models.BooleanField(default=True)),
                ('observaciones', models.TextField(blank=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Lote de Materia Prima',
                'verbose_name_plural': 'Lotes de Materia Prima',
                'ordering': ['-fecha_ingreso'],
            },
        ),
    ]
