# Generated by Django 6.0.3 on 2026-03-14 20:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('materia_prima', '0001_initial'),
        ('productos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='consumomateriaprima',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consumos_mp', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicallotemateriaprima',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicallotemateriaprima',
            name='producto',
            field=models.ForeignKey(blank=True, db_constraint=False, limit_choices_to={'categoria': 'MP'}, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='productos.producto'),
        ),
        migrations.AddField(
            model_name='lotemateriaprima',
            name='producto',
            field=models.ForeignKey(limit_choices_to={'categoria': 'MP'}, on_delete=django.db.models.deletion.PROTECT, related_name='lotes_mp', to='productos.producto'),
        ),
        migrations.AddField(
            model_name='consumomateriaprima',
            name='lote',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consumos', to='materia_prima.lotemateriaprima'),
        ),
        migrations.AlterUniqueTogether(
            name='lotemateriaprima',
            unique_together={('producto', 'numero_lote')},
        ),
    ]
