# Generated by Django 6.0.3 on 2026-03-14 20:56

import django.db.models.deletion
import django.utils.timezone
import simple_history.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('importaciones', '0001_initial'),
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FichaProveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contacto_nombre', models.CharField(blank=True, max_length=200)),
                ('contacto_email', models.EmailField(blank=True, max_length=254)),
                ('contacto_whatsapp', models.CharField(blank=True, max_length=30)),
                ('canal_habitual', models.CharField(choices=[('EMAIL', 'Email'), ('WHATSAPP', 'WhatsApp'), ('AMBOS', 'Email y WhatsApp')], default='EMAIL', max_length=10)),
                ('moneda_habitual', models.CharField(choices=[('USD', 'Dólar estadounidense'), ('EUR', 'Euro'), ('CNY', 'Yuan chino'), ('BRL', 'Real brasileño')], default='USD', max_length=5)),
                ('plazo_pago_dias', models.PositiveIntegerField(default=0, help_text='Días de plazo para pago desde la factura')),
                ('modalidad_pago', models.CharField(blank=True, help_text='Transferencia bancaria / Pago anticipado / Cuenta corriente', max_length=200)),
                ('notas', models.TextField(blank=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Ficha de Proveedor',
                'verbose_name_plural': 'Fichas de Proveedores',
            },
        ),
        migrations.CreateModel(
            name='HistoricalPago',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('modalidad', models.CharField(choices=[('TRANSFERENCIA', 'Transferencia bancaria internacional'), ('ANTICIPO', 'Pago anticipado'), ('CTA_CTE', 'Cuenta corriente')], max_length=20)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('moneda', models.CharField(default='USD', max_length=5)),
                ('tipo_cambio', models.DecimalField(blank=True, decimal_places=4, help_text='Tipo de cambio al momento de realizar la transferencia', max_digits=10, null=True)),
                ('fecha_vencimiento', models.DateField(help_text='Fecha límite para realizar el pago sin penalidades')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('PAGADO', 'Pagado'), ('VENCIDO', 'Vencido')], default='PENDIENTE', max_length=15)),
                ('fecha_pago', models.DateField(blank=True, null=True)),
                ('comprobante', models.TextField(blank=True, help_text='Comprobante bancario o confirmación de transferencia', max_length=100, null=True)),
                ('notas', models.TextField(blank=True)),
                ('creado_en', models.DateTimeField(blank=True, editable=False)),
                ('actualizado_en', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical Pago',
                'verbose_name_plural': 'historical Pagos',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modalidad', models.CharField(choices=[('TRANSFERENCIA', 'Transferencia bancaria internacional'), ('ANTICIPO', 'Pago anticipado'), ('CTA_CTE', 'Cuenta corriente')], max_length=20)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('moneda', models.CharField(default='USD', max_length=5)),
                ('tipo_cambio', models.DecimalField(blank=True, decimal_places=4, help_text='Tipo de cambio al momento de realizar la transferencia', max_digits=10, null=True)),
                ('fecha_vencimiento', models.DateField(help_text='Fecha límite para realizar el pago sin penalidades')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('PAGADO', 'Pagado'), ('VENCIDO', 'Vencido')], default='PENDIENTE', max_length=15)),
                ('fecha_pago', models.DateField(blank=True, null=True)),
                ('comprobante', models.FileField(blank=True, help_text='Comprobante bancario o confirmación de transferencia', null=True, upload_to='pagos/comprobantes/')),
                ('notas', models.TextField(blank=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Pago',
                'verbose_name_plural': 'Pagos',
                'ordering': ['fecha_vencimiento'],
            },
        ),
        migrations.CreateModel(
            name='Comunicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('COTIZACION', 'Solicitud de cotización'), ('CONFIRMACION', 'Confirmación de orden de compra'), ('SEGUIMIENTO', 'Seguimiento de embarque'), ('RECLAMO', 'Reclamo / Incidencia'), ('OTRO', 'Otro')], max_length=20)),
                ('canal', models.CharField(choices=[('EMAIL', 'Email'), ('WHATSAPP', 'WhatsApp'), ('LLAMADA', 'Llamada telefónica'), ('OTRO', 'Otro')], max_length=10)),
                ('resumen', models.TextField(help_text='Resumen del contenido de la comunicación')),
                ('adjunto', models.FileField(blank=True, null=True, upload_to='comunicaciones/')),
                ('fecha_hora', models.DateTimeField(default=django.utils.timezone.now)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('importacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comunicaciones', to='importaciones.importacion')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='comunicaciones', to='productos.proveedor')),
            ],
            options={
                'verbose_name': 'Comunicación',
                'verbose_name_plural': 'Comunicaciones',
                'ordering': ['-fecha_hora'],
            },
        ),
    ]
