# Generated by Django 6.0.3 on 2026-03-14 20:56

import simple_history.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CambioEstadoImportacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_anterior', models.CharField(blank=True, choices=[('ORDENADO', 'Ordenado'), ('EN_TRANSITO', 'En tránsito'), ('EN_ADUANA', 'En aduana'), ('DESPACHADO', 'Despachado'), ('RECIBIDO', 'Recibido'), ('CANCELADO', 'Cancelado')], max_length=15)),
                ('estado_nuevo', models.CharField(choices=[('ORDENADO', 'Ordenado'), ('EN_TRANSITO', 'En tránsito'), ('EN_ADUANA', 'En aduana'), ('DESPACHADO', 'Despachado'), ('RECIBIDO', 'Recibido'), ('CANCELADO', 'Cancelado')], max_length=15)),
                ('notas', models.TextField(blank=True)),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Cambio de Estado de Importación',
                'ordering': ['-fecha_hora'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalImportacion',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('numero_orden', models.CharField(db_index=True, help_text='Número interno de orden de compra', max_length=50)),
                ('estado', models.CharField(choices=[('ORDENADO', 'Ordenado'), ('EN_TRANSITO', 'En tránsito'), ('EN_ADUANA', 'En aduana'), ('DESPACHADO', 'Despachado'), ('RECIBIDO', 'Recibido'), ('CANCELADO', 'Cancelado')], default='ORDENADO', max_length=15)),
                ('fecha_orden', models.DateField()),
                ('fecha_embarque', models.DateField(blank=True, null=True)),
                ('fecha_eta', models.DateField(blank=True, help_text='Estimated Time of Arrival', null=True)),
                ('fecha_recepcion', models.DateField(blank=True, help_text='Fecha real de ingreso al depósito', null=True)),
                ('numero_tracking', models.CharField(blank=True, max_length=200)),
                ('referencia_embarque', models.CharField(blank=True, max_length=200)),
                ('costo_estimado_usd', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('moneda', models.CharField(default='USD', max_length=10)),
                ('notas', models.TextField(blank=True)),
                ('creado_en', models.DateTimeField(blank=True, editable=False)),
                ('actualizado_en', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical Importación',
                'verbose_name_plural': 'historical Importaciones',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Importacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_orden', models.CharField(help_text='Número interno de orden de compra', max_length=50, unique=True)),
                ('estado', models.CharField(choices=[('ORDENADO', 'Ordenado'), ('EN_TRANSITO', 'En tránsito'), ('EN_ADUANA', 'En aduana'), ('DESPACHADO', 'Despachado'), ('RECIBIDO', 'Recibido'), ('CANCELADO', 'Cancelado')], default='ORDENADO', max_length=15)),
                ('fecha_orden', models.DateField()),
                ('fecha_embarque', models.DateField(blank=True, null=True)),
                ('fecha_eta', models.DateField(blank=True, help_text='Estimated Time of Arrival', null=True)),
                ('fecha_recepcion', models.DateField(blank=True, help_text='Fecha real de ingreso al depósito', null=True)),
                ('numero_tracking', models.CharField(blank=True, max_length=200)),
                ('referencia_embarque', models.CharField(blank=True, max_length=200)),
                ('costo_estimado_usd', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('moneda', models.CharField(default='USD', max_length=10)),
                ('notas', models.TextField(blank=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Importación',
                'verbose_name_plural': 'Importaciones',
                'ordering': ['-fecha_orden'],
            },
        ),
        migrations.CreateModel(
            name='ItemImportacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_ordenada', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cantidad_recibida', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('precio_unitario_usd', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
            ],
            options={
                'verbose_name': 'Ítem de Importación',
                'verbose_name_plural': 'Ítems de Importación',
            },
        ),
    ]
