# Generated by Django 6.0.3 on 2026-03-14 20:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('importaciones', '0001_initial'),
        ('productos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cambioestadoimportacion',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalimportacion',
            name='creado_por',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalimportacion',
            name='despachante',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Usuario despachante responsable del trámite aduanero', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalimportacion',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalimportacion',
            name='proveedor',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='productos.proveedor'),
        ),
        migrations.AddField(
            model_name='importacion',
            name='creado_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='importaciones_creadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='importacion',
            name='despachante',
            field=models.ForeignKey(blank=True, help_text='Usuario despachante responsable del trámite aduanero', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='importaciones_despachadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='importacion',
            name='proveedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='importaciones', to='productos.proveedor'),
        ),
        migrations.AddField(
            model_name='cambioestadoimportacion',
            name='importacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cambios_estado', to='importaciones.importacion'),
        ),
        migrations.AddField(
            model_name='itemimportacion',
            name='importacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_set', to='importaciones.importacion'),
        ),
        migrations.AddField(
            model_name='itemimportacion',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items_importacion', to='productos.producto'),
        ),
        migrations.AddField(
            model_name='importacion',
            name='items',
            field=models.ManyToManyField(related_name='importaciones', through='importaciones.ItemImportacion', to='productos.producto'),
        ),
        migrations.AlterUniqueTogether(
            name='itemimportacion',
            unique_together={('importacion', 'producto')},
        ),
    ]
