# Generated by Django 6.0.3 on 2026-03-16 23:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('importaciones', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cambioestadoimportacion',
            options={'ordering': ['-fecha_hora'], 'verbose_name': 'Cambio de Estado de Importacion'},
        ),
        migrations.AlterModelOptions(
            name='historicalimportacion',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Importacion', 'verbose_name_plural': 'historical Importaciones'},
        ),
        migrations.AlterModelOptions(
            name='importacion',
            options={'ordering': ['-fecha_orden'], 'verbose_name': 'Importacion', 'verbose_name_plural': 'Importaciones'},
        ),
        migrations.AlterModelOptions(
            name='itemimportacion',
            options={'verbose_name': 'Item de Importacion', 'verbose_name_plural': 'Items de Importacion'},
        ),
        migrations.AddField(
            model_name='historicalimportacion',
            name='alerta_despacho_pendiente',
            field=models.BooleanField(default=False, help_text='True cuando paso la fecha ETA y aun no se cargo el despacho'),
        ),
        migrations.AddField(
            model_name='historicalimportacion',
            name='despacho',
            field=models.TextField(blank=True, help_text='Adjuntar documentacion de despacho aduanero', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='historicalimportacion',
            name='fecha_despacho',
            field=models.DateField(blank=True, help_text='Fecha real del despacho aduanero', null=True),
        ),
        migrations.AddField(
            model_name='historicalimportacion',
            name='guia_transporte',
            field=models.TextField(blank=True, help_text='Adjuntar guia de transporte o Bill of Lading', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='historicalimportacion',
            name='numero_bl',
            field=models.CharField(blank=True, help_text='Numero de BL o guia de transporte', max_length=100),
        ),
        migrations.AddField(
            model_name='historicalimportacion',
            name='numero_despacho',
            field=models.CharField(blank=True, help_text='Numero de despacho aduanero', max_length=100),
        ),
        migrations.AddField(
            model_name='historicalimportacion',
            name='numero_proforma',
            field=models.CharField(blank=True, help_text='Numero de proforma del proveedor', max_length=100),
        ),
        migrations.AddField(
            model_name='historicalimportacion',
            name='proforma',
            field=models.TextField(blank=True, help_text='Adjuntar proforma del proveedor (PDF, imagen, etc.)', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='importacion',
            name='alerta_despacho_pendiente',
            field=models.BooleanField(default=False, help_text='True cuando paso la fecha ETA y aun no se cargo el despacho'),
        ),
        migrations.AddField(
            model_name='importacion',
            name='despacho',
            field=models.FileField(blank=True, help_text='Adjuntar documentacion de despacho aduanero', null=True, upload_to='importaciones/despachos/'),
        ),
        migrations.AddField(
            model_name='importacion',
            name='fecha_despacho',
            field=models.DateField(blank=True, help_text='Fecha real del despacho aduanero', null=True),
        ),
        migrations.AddField(
            model_name='importacion',
            name='guia_transporte',
            field=models.FileField(blank=True, help_text='Adjuntar guia de transporte o Bill of Lading', null=True, upload_to='importaciones/guias/'),
        ),
        migrations.AddField(
            model_name='importacion',
            name='numero_bl',
            field=models.CharField(blank=True, help_text='Numero de BL o guia de transporte', max_length=100),
        ),
        migrations.AddField(
            model_name='importacion',
            name='numero_despacho',
            field=models.CharField(blank=True, help_text='Numero de despacho aduanero', max_length=100),
        ),
        migrations.AddField(
            model_name='importacion',
            name='numero_proforma',
            field=models.CharField(blank=True, help_text='Numero de proforma del proveedor', max_length=100),
        ),
        migrations.AddField(
            model_name='importacion',
            name='proforma',
            field=models.FileField(blank=True, help_text='Adjuntar proforma del proveedor (PDF, imagen, etc.)', null=True, upload_to='importaciones/proformas/'),
        ),
        migrations.AlterField(
            model_name='cambioestadoimportacion',
            name='estado_anterior',
            field=models.CharField(blank=True, choices=[('ORDENADO', 'Ordenado'), ('EN_TRANSITO', 'En transito'), ('EN_ADUANA', 'En aduana'), ('DESPACHADO', 'Despachado'), ('RECIBIDO', 'Recibido'), ('CANCELADO', 'Cancelado')], max_length=15),
        ),
        migrations.AlterField(
            model_name='cambioestadoimportacion',
            name='estado_nuevo',
            field=models.CharField(choices=[('ORDENADO', 'Ordenado'), ('EN_TRANSITO', 'En transito'), ('EN_ADUANA', 'En aduana'), ('DESPACHADO', 'Despachado'), ('RECIBIDO', 'Recibido'), ('CANCELADO', 'Cancelado')], max_length=15),
        ),
        migrations.AlterField(
            model_name='historicalimportacion',
            name='despachante',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='historicalimportacion',
            name='estado',
            field=models.CharField(choices=[('ORDENADO', 'Ordenado'), ('EN_TRANSITO', 'En transito'), ('EN_ADUANA', 'En aduana'), ('DESPACHADO', 'Despachado'), ('RECIBIDO', 'Recibido'), ('CANCELADO', 'Cancelado')], default='ORDENADO', max_length=15),
        ),
        migrations.AlterField(
            model_name='historicalimportacion',
            name='fecha_recepcion',
            field=models.DateField(blank=True, help_text='Fecha real de ingreso al deposito', null=True),
        ),
        migrations.AlterField(
            model_name='historicalimportacion',
            name='numero_orden',
            field=models.CharField(db_index=True, help_text='Numero interno de orden de compra', max_length=50),
        ),
        migrations.AlterField(
            model_name='importacion',
            name='despachante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='importaciones_despachadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='importacion',
            name='estado',
            field=models.CharField(choices=[('ORDENADO', 'Ordenado'), ('EN_TRANSITO', 'En transito'), ('EN_ADUANA', 'En aduana'), ('DESPACHADO', 'Despachado'), ('RECIBIDO', 'Recibido'), ('CANCELADO', 'Cancelado')], default='ORDENADO', max_length=15),
        ),
        migrations.AlterField(
            model_name='importacion',
            name='fecha_recepcion',
            field=models.DateField(blank=True, help_text='Fecha real de ingreso al deposito', null=True),
        ),
        migrations.AlterField(
            model_name='importacion',
            name='numero_orden',
            field=models.CharField(help_text='Numero interno de orden de compra', max_length=50, unique=True),
        ),
        migrations.CreateModel(
            name='LoteImportacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_lote', models.CharField(max_length=100)),
                ('cantidad_inicial', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cantidad_actual', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estado', models.CharField(choices=[('BLOQUEADO', 'Bloqueado - pendiente ANMAT'), ('LIBERADO', 'Liberado - disponible'), ('AGOTADO', 'Agotado')], default='LIBERADO', max_length=20)),
                ('fecha_ingreso', models.DateField()),
                ('fecha_vencimiento', models.DateField(blank=True, null=True)),
                ('certificado_calidad', models.FileField(blank=True, null=True, upload_to='importaciones/lotes/certificados/')),
                ('observaciones', models.TextField(blank=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lotes', to='importaciones.itemimportacion')),
            ],
            options={
                'verbose_name': 'Lote de Importacion',
                'verbose_name_plural': 'Lotes de Importacion',
                'ordering': ['-fecha_ingreso'],
            },
        ),
    ]
