# Generated by Django 6.0.3 on 2026-03-17 00:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('importaciones', '0003_alter_cambioestadoimportacion_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequisitoCalidadImportacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('FOTO', 'Foto del producto'), ('PLANO', 'Plano tecnico'), ('CERT_MP', 'Certificado de materia prima'), ('CLV', 'CLV'), ('CARTA', 'Carta compromiso'), ('OTRO', 'Otro')], help_text='Tipo de documento de calidad', max_length=20)),
                ('descripcion', models.CharField(blank=True, help_text='Descripcion adicional del documento', max_length=200)),
                ('archivo', models.FileField(help_text='Archivo del documento (PDF, imagen, etc.)', upload_to='importaciones/calidad/')),
                ('fecha_carga', models.DateTimeField(auto_now_add=True)),
                ('vigente', models.BooleanField(default=True)),
                ('importacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requisitos_calidad', to='importaciones.importacion')),
            ],
            options={
                'verbose_name': 'Requisito de Calidad',
                'verbose_name_plural': 'Requisitos de Calidad',
                'ordering': ['tipo', '-fecha_carga'],
            },
        ),
    ]
