# Generated by Django 6.0.3 on 2026-03-17 00:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('importaciones', '0004_requisitocalidadimportacion'),
        ('productos', '0004_remove_producto_sectores'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalimportacion',
            name='sector_destino',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Sector de la fabrica al que se destinan los productos de esta OC', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='productos.sector'),
        ),
        migrations.AddField(
            model_name='importacion',
            name='sector_destino',
            field=models.ForeignKey(blank=True, help_text='Sector de la fabrica al que se destinan los productos de esta OC', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='importaciones', to='productos.sector'),
        ),
    ]
