# Generated by Django 6.0.3 on 2026-03-17 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('importaciones', '0005_historicalimportacion_sector_destino_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalimportacion',
            name='fecha_entrega_sector',
            field=models.DateField(blank=True, help_text='Fecha estimada de entrega al sector', null=True),
        ),
        migrations.AddField(
            model_name='historicalimportacion',
            name='notas_sector',
            field=models.TextField(blank=True, help_text='Notas adicionales sobre la entrega al sector'),
        ),
        migrations.AddField(
            model_name='historicalimportacion',
            name='responsable_sector',
            field=models.CharField(blank=True, help_text='Nombre del responsable del sector que recibe los productos', max_length=200),
        ),
        migrations.AddField(
            model_name='importacion',
            name='fecha_entrega_sector',
            field=models.DateField(blank=True, help_text='Fecha estimada de entrega al sector', null=True),
        ),
        migrations.AddField(
            model_name='importacion',
            name='notas_sector',
            field=models.TextField(blank=True, help_text='Notas adicionales sobre la entrega al sector'),
        ),
        migrations.AddField(
            model_name='importacion',
            name='responsable_sector',
            field=models.CharField(blank=True, help_text='Nombre del responsable del sector que recibe los productos', max_length=200),
        ),
    ]
