# Generated by Django 6.0.3 on 2026-03-14 20:56

import simple_history.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CambioEstadoANMAT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_anterior', models.CharField(blank=True, choices=[('PRESENTADO', 'Presentado'), ('EN_TRAMITE', 'En trámite'), ('OBSERVADO', 'Observado'), ('PAGO_VEP', 'Pago de VEP faltante'), ('FINALIZADO', 'Finalizado - Aprobado'), ('RECHAZADO', 'Rechazado')], max_length=20)),
                ('estado_nuevo', models.CharField(choices=[('PRESENTADO', 'Presentado'), ('EN_TRAMITE', 'En trámite'), ('OBSERVADO', 'Observado'), ('PAGO_VEP', 'Pago de VEP faltante'), ('FINALIZADO', 'Finalizado - Aprobado'), ('RECHAZADO', 'Rechazado')], max_length=20)),
                ('notas', models.TextField(blank=True)),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Cambio de Estado ANMAT',
                'ordering': ['-fecha_hora'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalTramiteANMAT',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('estado', models.CharField(choices=[('PRESENTADO', 'Presentado'), ('EN_TRAMITE', 'En trámite'), ('OBSERVADO', 'Observado'), ('PAGO_VEP', 'Pago de VEP faltante'), ('FINALIZADO', 'Finalizado - Aprobado'), ('RECHAZADO', 'Rechazado')], default='PRESENTADO', max_length=20)),
                ('fecha_presentacion', models.DateField()),
                ('numero_expediente', models.CharField(blank=True, max_length=100)),
                ('documento_14_puntos', models.TextField(blank=True, max_length=100, null=True)),
                ('observaciones_anmat', models.TextField(blank=True, help_text='Texto de las observaciones recibidas de ANMAT (si aplica)')),
                ('respuesta_observaciones', models.TextField(blank=True, max_length=100, null=True)),
                ('numero_vep', models.CharField(blank=True, max_length=100)),
                ('monto_vep', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('fecha_pago_vep', models.DateField(blank=True, null=True)),
                ('fecha_finalizacion', models.DateField(blank=True, null=True)),
                ('certificado_aprobacion', models.TextField(blank=True, max_length=100, null=True)),
                ('notas', models.TextField(blank=True)),
                ('creado_en', models.DateTimeField(blank=True, editable=False)),
                ('actualizado_en', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical Trámite ANMAT',
                'verbose_name_plural': 'historical Trámites ANMAT',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='TramiteANMAT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('PRESENTADO', 'Presentado'), ('EN_TRAMITE', 'En trámite'), ('OBSERVADO', 'Observado'), ('PAGO_VEP', 'Pago de VEP faltante'), ('FINALIZADO', 'Finalizado - Aprobado'), ('RECHAZADO', 'Rechazado')], default='PRESENTADO', max_length=20)),
                ('fecha_presentacion', models.DateField()),
                ('numero_expediente', models.CharField(blank=True, max_length=100)),
                ('documento_14_puntos', models.FileField(blank=True, null=True, upload_to='anmat/14_puntos/')),
                ('observaciones_anmat', models.TextField(blank=True, help_text='Texto de las observaciones recibidas de ANMAT (si aplica)')),
                ('respuesta_observaciones', models.FileField(blank=True, null=True, upload_to='anmat/respuestas/')),
                ('numero_vep', models.CharField(blank=True, max_length=100)),
                ('monto_vep', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('fecha_pago_vep', models.DateField(blank=True, null=True)),
                ('fecha_finalizacion', models.DateField(blank=True, null=True)),
                ('certificado_aprobacion', models.FileField(blank=True, null=True, upload_to='anmat/certificados/')),
                ('notas', models.TextField(blank=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Trámite ANMAT',
                'verbose_name_plural': 'Trámites ANMAT',
                'ordering': ['-fecha_presentacion'],
            },
        ),
    ]
