# Generated by Django 6.0.3 on 2026-03-14 20:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('anmat', '0001_initial'),
        ('importaciones', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cambioestadoanmat',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicaltramiteanmat',
            name='despachante',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicaltramiteanmat',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicaltramiteanmat',
            name='importacion',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='importaciones.importacion'),
        ),
        migrations.AddField(
            model_name='tramiteanmat',
            name='despachante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tramites_anmat', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tramiteanmat',
            name='importacion',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='tramite_anmat', to='importaciones.importacion'),
        ),
        migrations.AddField(
            model_name='cambioestadoanmat',
            name='tramite',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cambios_estado', to='anmat.tramiteanmat'),
        ),
    ]
