# Generated by Django 6.0.3 on 2026-03-16 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anmat', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicaltramiteanmat',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Tramite ANMAT', 'verbose_name_plural': 'historical Tramites ANMAT'},
        ),
        migrations.AlterModelOptions(
            name='tramiteanmat',
            options={'ordering': ['-fecha_presentacion'], 'verbose_name': 'Tramite ANMAT', 'verbose_name_plural': 'Tramites ANMAT'},
        ),
        migrations.AddField(
            model_name='historicaltramiteanmat',
            name='comprobante_vep',
            field=models.TextField(blank=True, help_text='Adjuntar comprobante de pago del VEP (PDF, imagen, etc.)', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tramiteanmat',
            name='comprobante_vep',
            field=models.FileField(blank=True, help_text='Adjuntar comprobante de pago del VEP (PDF, imagen, etc.)', null=True, upload_to='anmat/comprobantes_vep/'),
        ),
        migrations.AlterField(
            model_name='cambioestadoanmat',
            name='estado_anterior',
            field=models.CharField(blank=True, choices=[('PRESENTADO', 'Presentado'), ('EN_TRAMITE', 'En tramite'), ('OBSERVADO', 'Observado'), ('PAGO_VEP', 'Pago de VEP faltante'), ('FINALIZADO', 'Finalizado - Aprobado'), ('RECHAZADO', 'Rechazado')], max_length=20),
        ),
        migrations.AlterField(
            model_name='cambioestadoanmat',
            name='estado_nuevo',
            field=models.CharField(choices=[('PRESENTADO', 'Presentado'), ('EN_TRAMITE', 'En tramite'), ('OBSERVADO', 'Observado'), ('PAGO_VEP', 'Pago de VEP faltante'), ('FINALIZADO', 'Finalizado - Aprobado'), ('RECHAZADO', 'Rechazado')], max_length=20),
        ),
        migrations.AlterField(
            model_name='historicaltramiteanmat',
            name='estado',
            field=models.CharField(choices=[('PRESENTADO', 'Presentado'), ('EN_TRAMITE', 'En tramite'), ('OBSERVADO', 'Observado'), ('PAGO_VEP', 'Pago de VEP faltante'), ('FINALIZADO', 'Finalizado - Aprobado'), ('RECHAZADO', 'Rechazado')], default='PRESENTADO', max_length=20),
        ),
        migrations.AlterField(
            model_name='tramiteanmat',
            name='estado',
            field=models.CharField(choices=[('PRESENTADO', 'Presentado'), ('EN_TRAMITE', 'En tramite'), ('OBSERVADO', 'Observado'), ('PAGO_VEP', 'Pago de VEP faltante'), ('FINALIZADO', 'Finalizado - Aprobado'), ('RECHAZADO', 'Rechazado')], default='PRESENTADO', max_length=20),
        ),
    ]
